#!/usr/bin/env bash
[ -z "$1" ] && echo "Useage: $0 <hostname> [up]" && exit 1
[ -n "$1" ] && hostname=$1 && shift 1 &&\
[ -n "$1" ] && [ "$1" == "up" ] && isUp="-u" && shift 1
FLAKE=${FLAKE:-"$(realpath "$(dirname "$(readlink -f "$0")")")/.."} && export FLAKE &&\
nix --extra-experimental-features "nix-command flakes" run nixpkgs#nh -- os switch -v $isUp -H "$hostname" -- --show-trace "$@"
